services:
  postgres:
    image: postgres:15-alpine
    container_name: expe-postgres
    environment:
      POSTGRES_USER: expe_user
      POSTGRES_PASSWORD: expe_password
      POSTGRES_DB: expe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expe_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Postgres Prometheus exporter
  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: expe-postgres-exporter
    depends_on:
      - postgres
    environment:
      - DATA_SOURCE_NAME=postgresql://expe_user:expe_password@postgres:5432/expe_db?sslmode=disable
    ports:
      - "9187:9187"

  redis:
    image: redis:7-alpine
    container_name: expe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Redis Prometheus exporter
  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: expe-redis-exporter
    depends_on:
      - redis
    command:
      - '--redis.addr=redis://redis:6379'
    ports:
      - "9121:9121"

  # Prometheus for scraping app metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: expe-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: expe-grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
