# Simple Docker Compose for Postgres and Redis only
# Run frontend and backend with PM2 on the host

services:
  postgres:
    image: postgres:15-alpine
    container_name: expe-postgres
    environment:
      POSTGRES_USER: expe_user
      POSTGRES_PASSWORD: expe_password
      POSTGRES_DB: expe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expe_user"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7-alpine
    container_name: expe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5


volumes:
  postgres_data:
  redis_data:
